### ISSUE TITLE
Move Countdown Timer functionality in a service

### ISSUE THREAD

**Issue by lakshmikantdeshpande** [Legendarywicho/Pomodoro#3]
Hey @Legendarywicho,
If a user closes the app (from recents), it will stop the timer. To avoid that we can move this CountdownTimer functionality to a service. We don't have a lot of functionality in the CountdownTimer class, so simply we can use a Thread as well.
Here's a code snippet of my idea: 

        if (!isStarted) {
            new Thread(new Runnable() {
                @Override
                public void run() {

                    try {
                        if (!Thread.interrupted() || is) {
                            Thread.sleep(1000);
                            setCurrentSeconds(++currentSecond);
                        } else {
                            setCurrentSeconds(0);
                            isStarted = false;
                        }
                    } catch (InterruptedException ie) {
                        Log.i(TAG, "Interrupted");
                        setCurrentSeconds(0);
                        isStarted = false;
                    }
                }
            }).start();
        }
Also we can have a persistent notification, which will allow a user to pause / resume / stop the timer.
Let me know what do you think.

**Comment by luissantiagodev** [comment]
Hey @lakshmikantdeshpande, 
I actually noticed that I couple of days ago, What I did on the onFinish() method:

```
 if(minutesToStart == 0 || minutesToStart<0 && currentSecond == 1000){
                Log.e(TAG, "Im inside the condition");
                setUpNotification();
                resetMinutes();

            }
            else{
                minutesToStart-=1;
                mSecondsTextView.setText(String.valueOf(currentSecond));
                //We restart the seconds so we dont have negative values
                currentSecond = 60000;
                mMinutesTextview.setText(String.valueOf(minutesToStart));
                //We start our onTick()
                start();
            }
```

With that the problem got solved, I've been testing it out it seems working okay,have you download the latest updates?
I was trying to implement threads at the beginning but i found this class in the android documentation and it seem okay, although having persistent notification would be great, even thought it's working now, should we change it? what do you think?

**Comment by lakshmikantdeshpande** [comment]
No, I haven't had a chance to test the latest app. I'll try it out. And I guess you're starting the timer when it gets stopped abruptly

**Comment by lakshmikantdeshpande** [comment]
And yes, I think we should add a persistent notification, that'd be cool !

**Comment by luissantiagodev** [comment]
Okay, I'll open a new branch for the persistent notification. It sounds awesome!, I just wanted to let you know that i published this app in the google play store, here is the link : https://play.google.com/store/apps/details?id=com.luis_santiago.flagquizapp&hl=en
